name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"   # publish on semantic version tags

permissions:
  contents: read
  id-token: write   # REQUIRED for Trusted Publishing (OIDC) 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: python -m pip install --upgrade pip build
      - run: python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          skip-existing: true
          verify-metadata: true
      - name: Verify tag matches package version
        shell: python
        run: |
          import tomllib, os, sys
          tag = os.environ["GITHUB_REF_NAME"].lstrip("v")
          with open("pyproject.toml","rb") as f:
              version = tomllib.load(f)["project"]["version"]
          if tag != version:
              print(f"Tag {tag} != pyproject version {version}")
              sys.exit(1)
